### ISSUE TITLE
Update RubyGems

### ISSUE THREAD

**Issue by trev** [zeptofs/aba#1]
Your readme documentation is for 0.2,0 which is only available on GitHub. RubyGems only has 0.1.0. I had to do `gem 'aba', git: 'https://github.com/andrba/aba.git'`.

You may want to update RubyGems. Thanks for the gem!

**Comment by trev** [comment]
Hey @andrba, would you be willing to let me be a maintainer for this gem? I've forked it an affected a bunch of changes and wouldn't mind getting it back to the community. Have a look at my fork at: https://github.com/krakendevelopments/aba

Still some more work to go, but you get the gist.

**Comment by andrba** [comment]
Great job @trev I can add you to the list of collaborators and give you push permissions on rubygems. What's your email address?

**Comment by trev** [comment]
Great! My email is my username at a07.com.au.  Cheers @andrba

**Comment by andrba** [comment]
You can merge and push it now. Thanks.
