### ISSUE TITLE
Amount validations

### ISSUE THREAD

**Issue by mcauser** [zeptofs/aba#13]
Found 3 little edge cases while testing.

1. You can put a `amount: 0` in `add_transaction` and `add_return` without error. Add a greater than 0 validation?

https://www.cemtexaba.com/aba-format/cemtex-aba-file-format-details
> Amount - Must be greater than zero.

2. Unrealistically large amounts overflow max 10 chars. Add a max length validation to amount?
eg `amount: 98765432100` (you know, when Bezos uses this)

3. Huge amounts cause the File Total Record net/credit/debit total amount fields to overflow max 10 chars each.
Validate sum of transactions 3x amount fields don't exceed 10 chars each?
Or more simply the full File Total Record doesn't exceed 120 chars?

**Comment by trev** [comment]
Resolved in https://github.com/andrba/aba/pull/14
