### ISSUE TITLE
Aba batch - User id

### ISSUE THREAD

**Issue by MichaelDorkhom** [zeptofs/aba#7]
I'm trying to create a batch with a 10 digit user_id, is there a reason why the validation limits it to 6?
Thanks!

**Comment by kiela** [comment]
Specification of ABA files requires no more then 6 digit for that field:

> Char Pos: 57-62
> Field Size: 6
> Field Description: Name of Use supplying file
> Specification: Must be User Identification Number which is allocated by APCA. Must be numeric, right justified, zero filled.

source: https://www.cemtexaba.com/aba-format/cemtex-aba-file-format-details#descriptive
