### ISSUE TITLE
Self Balanced file

### ISSUE THREAD

**Issue by marine44** [zeptofs/aba#8]
I have reviewed http://www.nab.com.au/content/dam/nabconnectcontent/file-formats/NAB%20Connect%20Consolidated%20File%20Format%20Specification_V0.05.pdf which is the NAB specification for ABA. (page 19-20)

They require a self-balanced file.

Does this gem support a self-balanced file?

**Comment by trev** [comment]
Hi @ryanharnwell, sorry for the delay, I somehow missed this. yes it supports self-balanced files.
